### PR TITLE
fix: improve alizer performances (#118)

### LINKED ISSUE #118: Investigate how speed up detection for big projects
I noticed that for complex projects with many components and files (~100k) it takes 1min to detect everything and select the right devfiles. This should be improved.

### PR DESCRIPTION
**Pull request by lstocchi**
it resolves #118 

This patch refactored some aspects of the detection to improve its speed. In some cases it went from 1m to less than 1 sec.

- fetching all files is now cached
- finding a file also works using an exact location, so it skips from running a regex on each path and it just look at that position (dir + filename) to check if it exists
- when performing a root detection, alizer still was fetching all files even if it was not needed and i removed the `no-config` languages detection from the root detection as it's useless. it needs to parse all files.

### CODE REVIEW

File: go/pkg/apis/recognizer/component_recognizer.go [hunk 1]
```diff
@@ -209,34 +195,66 @@ func isFirstPathParentOfSecond(firstPath string, secondPath string) bool {
...
+	if strings.EqualFold(language, "javascript") {
+		configFile = "jsconfig.json"
+	} else if strings.EqualFold(language, "typescript") {
+		configFile = "tsconfig.json"
+	}
+
+	if configFile == "" {
+		return true
+	}
+	if _, err := os.Stat(filepath.Join(dirPath, configFile)); os.IsNotExist(err) {
```
Comment (jeffmaury) [inline go/pkg/apis/recognizer/component_recognizer.go:249]: Not sure to fully understand: does it mean those files are required to a Javascript or Typescript component.

File: go/pkg/utils/cache.go [hunk 2]
```diff
@@ -0,0 +1,16 @@
+package utils
+
+var filePathsFromRoot = make(map[string][]string)
```
Comment (jeffmaury) [inline go/pkg/utils/cache.go:3]: My understanding is that the cache is a global and shared variable so if there are 2 executions of alizer then that may be incorrect and confusing so I would recommand to have the cache be part of an Alizer execution context that is created for each invocation of Alizer

**Review by jeffmaury — CHANGES_REQUESTED** [review]

File: go/pkg/utils/cache.go (hunk 2 above)
Comment (lstocchi) [reply go/pkg/utils/cache.go:3]: I don't get this. If there are 2 executions of alizer there will be 2 processes so i don't think this will be shared, but even if this happened, the map key is the path to being analyzed so the files list will always be the same. If you are executing 2 analysis at the same time it's unlikely the folder content changes.

File: go/pkg/apis/recognizer/component_recognizer.go (hunk 1 above)
Comment (lstocchi) [reply go/pkg/apis/recognizer/component_recognizer.go]: The idea was that one but after reading your comments and a bit of investigation i found out those files are not mandatory, so now i check if the typescript dependency is in the project, if so the main lang is typescript otherwise javascript

File: go/pkg/utils/cache.go (hunk 2 above)
Comment (jeffmaury) [reply go/pkg/utils/cache.go:3]: Alizer can be integrated in 2 ways: Go library or standalone executable. So my remark applies to the first use case

File: go/pkg/apis/enricher/framework/javascript/nodejs/express_detector.go [hunk 3]
```diff
@@ -31,8 +32,8 @@ func (e ExpressDetector) DoFrameworkDetection(language *model.Language, config s
 	}
 }
 
-func (e ExpressDetector) DoPortsDetection(component *model.Component) {
-	files, err := utils.GetFilePathsFromRoot(component.Path)
+func (e ExpressDetector) DoPortsDetection(component *model.Component, ctx *context.Context) {
+	files, err := utils.GetCachedFilePathsFromRoot(component.Path, ctx)
```
[the remark this answers is not in the document]
Comment (lstocchi) [reply go/pkg/apis/enricher/framework/javascript/nodejs/express_detector.go:36]: Unfortunately I cannot extend the context class as it's defined in a different package. The only thing i can do is to create a custom sub-package in my code. Something like
```
type myContext context.Context 
or
type myContext struct {
   *context.Context
}

then
func (c myContext) GetCachedFilePathsFromRoot
```
So it will become 
```
func (e ExpressDetector) DoPortsDetection(component *model.Component, ctx *myContext) {
	files, err := ctx.GetCachedFilePathsFromRoot(component.Path)
```
Do you prefer having this?

[the remark this answers is not in the document]
Comment (jeffmaury) [reply go/pkg/apis/enricher/framework/javascript/nodejs/express_detector.go:36]: OK I though context was an alyzer thing I did not catch it came from Go !!!!

**Review by jeffmaury — APPROVED** [review]
LGTM
